### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by Unaimend** [trustable-code/NiGui#133]
Moin Moin,
 I just wanted to know if this library is still being maintained I wanted to use it to write a GUI for a small application for a shop that my friend owns, so I'd like to know if you plan to work on this any further. Also would like to work on this myself, so maybe you write a little text how to add new stuff to nigui

Greetings from Schleswig Holstein
Thomas Dost

**Comment by 0xACE** [comment]
Hello Thomas.

Afaik, i see a fair amount of activity in this project in terms of discussions, meaning the project is not abandoned, my understanding is that he is doing the best he can with his limited time...

Because of the time constraint I'm guessing it's easier to just look at the commit history and some source files...

**Comment by Unaimend** [comment]
Thanks for your reply, I will see how far I get with this library and try to contribute as much as I can

**Comment by trustable-code** [comment]
Good question from Unaimend and good aswer from 0xACE.
The activity is low at the moment, but there are some users, including me. Probably I should do a code rewrite, because I'm not satisfied with the code quality and structure any more.

**Comment by enthus1ast** [comment]
@trustable-code please do it, NiGui is still my go to nim gui library, even if a lot of stuff is missing!
I'ts very nice to have a small self contained gui! Every time there is a change in NiGui i read the changes in the hope there is more nice stuff added.
