### ISSUE TITLE
Windows target (mingw) with forceGtk build fails to find GTK entry point.

### ISSUE THREAD

**Issue by UNIcodeX** [trustable-code/NiGui#39]
While building for a windows target works fine, using `-d:forceGtk` results in an error:
`The procedure entry point at atk_hyperlink_impl_get_type could not be located in the dynamic link library...`

![image](https://user-images.githubusercontent.com/8235002/55031745-41b10e00-4fdd-11e9-9ac4-32143736d52c.png)

I confirmed that the mentioned DLL does exist in the path given in the error message.

**Comment by trustable-code** [comment]
I have no idea, what tries to call the procedure ``atk_hyperlink_impl_get_type``. NiGui's Gtk binding does not include this procedure. Do other Gtk 3 programs work on your machine?

**Comment by UNIcodeX** [comment]
They do.

**Comment by aryanbadiee** [comment]
this problem is related to the nim compiler.
i examined this dll in a simple way and encountered the same error!
("libgtk-3-0.dll" exists in the directory)
![Nigui](https://user-images.githubusercontent.com/51372926/61162169-9f318200-a51c-11e9-8a82-8ea9d5b162b7.png)
in general, the nim compiler does not have the ability to read any dll file.
for example, i made dll file with flat assembler and used it in fasm & cpp but this dll file didn't load in nim

**Comment by trustable-code** [comment]
apparently no longer relevant, please re-open if still reproducible
