### ISSUE TITLE
Black pseudoshadow around text

### ISSUE THREAD

**Issue by Guevara-chan** [trustable-code/NiGui#83]
Consider following easy code:
```import nigui
app.init()

proc render_text(text: string, font: string): Image =
    result = newImage()
    result.resize 1, 1
    let canvas          = result.canvas
    canvas.fontFamily   = font
    canvas.fontSize     = 20
    canvas.textColor    = rgb(255, 0, 0)
    canvas.areaColor    = rgb(0, 0, 0, 0)
    result.resize canvas.getTextWidth(text), canvas.getTextLineHeight()
    canvas.fill()
    canvas.drawText text, 0, 0

let img = render_text("Hello, world !", "Sylfaen")
```
Save img. Look at img. See this:
![image](https://user-images.githubusercontent.com/8768470/70900427-d6dfb100-2009-11ea-9465-49917febdce2.png)

**Comment by trustable-code** [comment]
I can reproduce it under Windows.
I think the reason is the transparent areaColor.
Maybe `GdipDrawString()` can't handle a transparent background or there is the need to set a special mode. I will search for a solution.

Related: 
- https://stackoverflow.com/questions/42221322/how-to-draw-text-with-transparency-using-gdi
- https://www.autoitscript.com/forum/topic/191994-text-to-png-bold-ugly-text-on-transparent-background-gdiplus/

**Comment by trustable-code** [comment]
With TextRenderingHint_AntiAlias the black shadow is gone.
Before:
![before](https://user-images.githubusercontent.com/8593614/70995194-4324e800-20d0-11ea-895d-f82ab30b3e96.png)
After:
![after](https://user-images.githubusercontent.com/8593614/70995193-4324e800-20d0-11ea-9911-a20bedd407f2.png)
